version: "3"

services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/sites-enable:/etc/nginx/sites-enable
      - ${CERTBOT_DIR}:/var/www/html
      - ${CERT_DIR}:/etc/letsencrypt
      - ${NGINX_LOG_DIR}:/var/log/nginx
    logging:
      driver: syslog
      options:
        tag: "[nginx]"

