#!/bin/sh

# MIT License
#
# Copyright (c) 2021-2023 Kazuhito Suda
#
# This file is part of FIWARE Big Bang
#
# https://github.com/lets-fiware/FIWARE-Big-Bang
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -ue

cd "$(dirname "$0")"
cd ../..

. ./config.sh

if [ "${ORION}" != "orion" ]; then
  echo "Error ORION value in config.sh"
  exit 1
fi

if [ "${KEYROCK}" != "keyrock" ]; then
  echo "Error ORION value in config.sh"
  exit 1
fi

for NAME in CYGNUS COMET QUANTUMLEAP WIRECLOUD NGSIPROXY NODE_RED GRAFANA ELASTICSEARCH IDM_ADMIN_USER IDM_ADMIN_EMAIL IDM_ADMIN_PASS FIREWALL CERT_EMAIL CERT_REVOKE CERT_TEST CERT_FORCE_RENEWAL KEYROCK_POSTGRES IOTAGENT_UL IOTAGENT_JSON IOTAGENT_HTTP IOTA_HTTP_AUTH IOTA_HTTP_BASIC_USER IOTA_HTTP_BASIC_PASS MQTT_USERNAME MQTT_PASSWORD MOSQUITTO MQTT_TLS MQTT_1883 NODE_RED_INSTANCE_NUMBER NODE_RED_INSTANCE_USERNAME NODE_RED_INSTANCE_HTTP_NODE_ROOT NODE_RED_INSTANCE_HTTP_ADMIN_ROOT NODE_RED_LOGGING_METRICS NODE_RED_LOGGING_AUDIT QUERYPROXY REGPROXY REGPROXY_NGSITYPE REGPROXY_HOST REGPROXY_IDMTYPE REGPROXY_IDMHOST REGPROXY_USERNAME REGPROXY_PASSWORD REGPROXY_CLIENT_ID REGPROXY_CLIENT_SECRET POSTFIX CYGNUS_MONGO CYGNUS_MYSQL CYGNUS_POSTGRES CYGNUS_ELASTICSEARCH PERSEO PERSEO_MAX_AGE PERSEO_SMTP_HOST PERSEO_SMTP_PORT PERSEO_SMTP_SECURE PERSEO_LOG_LEVEL MULTI_SERVER_KEYROCK MULTI_SERVER_ADMIN_EMAIL MULTI_SERVER_ADMIN_PASS MULTI_SERVER_CLIENT_ID MULTI_SERVER_CLIENT_SECRET ORION_EXPOSE_PORT CYGNUS_EXPOSE_PORT ELASTICSEARCH_EXPOSE_PORT COMET_EXPOSE_PORT QUANTUMLEAP_EXPOSE_PORT MONGO_EXPOSE_PORT MYSQL_EXPOSE_PORT POSTGRES_EXPOSE_PORT MULTI_SERVER_KEYROCK MULTI_SERVER_ADMIN_EMAIL MULTI_SERVER_ADMIN_PASS MULTI_SERVER_PEP_PROXY_USERNAME MULTI_SERVER_PEP_PASSWORD MULTI_SERVER_CLIENT_ID MULTI_SERVER_CLIENT_SECRET MULTI_SERVER_ORION_HOST MULTI_SERVER_QUANTUMLEAP_HOST MULTI_SERVER_ORION_INTERNAL_IP DRACO DRACO_DISABLE_NIFI_DOCS DRACO_MONGO DRACO_MYSQL DRACO_POSTGRES DRACO_EXPOSE_PORT ORION_LD ORION_LD_EXPOSE_PORT MINTAKA MINTAKA_EXPOSE_PORT TIMESCALE_PASS TIMESCALE_EXPOSE_PORT ZEPPELIN ZEPPELIN_DEBUG
do
  eval VAL=\"\$$NAME\"
  if [ -n "$VAL" ]; then
    echo "${NAME} not empty: ${VAL}"
    exit 1
  fi
done

if [ "${IMAGE_CERTBOT}" != "certbot/certbot:v2.6.0" ]; then
  echo "Error IMAGE_CERTBOT"
  exit 1
fi
