name: Dockerfile
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-dockerfiles:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Run Hadolint Dockerfile Linter
        run: test/script/lint-dockerfile.sh
